WebDriverException not defined (#139)
I didn't have chromedriver installed initially - it caused a secondary exception. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tcrha/.local/bin/deletefb", line 8, in <module>
    sys.exit(run_delete())
  File "/home/tcrha/.local/lib/python3.8/site-packages/deletefb/deletefb.py", line 112, in run_delete
    driver = login(
  File "/home/tcrha/.local/lib/python3.8/site-packages/deletefb/tools/login.py", line 44, in login
    driver = setup_selenium(chrome_options, chrome_binary_path)
  File "/home/tcrha/.local/lib/python3.8/site-packages/deletefb/tools/chrome_driver.py", line 66, in setup_selenium
    except WebDriverException:
NameError: name 'WebDriverException' is not defined